trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  testResultsDir: '$(Build.ArtifactStagingDirectory)\TestResults'

steps:
  # Setup Python
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
    displayName: 'Install Python'

  # Install Dependencies
  - script: |
      if not exist requirements.txt (
        echo "Error: requirements.txt not found!" && exit /b 1
      )
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Dependencies'

  # Run Tests
  - script: |
      mkdir $(testResultsDir)
      pabot --processes 8 --outputdir $(testResultsDir)
    displayName: 'Running Robot Tests'

  # Convert to JUnit Format (Optional)
  - script: |
      pip install robotframework-junitxml
      rebot --xunit $(testResultsDir)\output.xml
    condition: always()  
    displayName: 'Convert Robot Results to JUnit Format'

  # Publish Results Directory
  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: '$(testResultsDir)'
      ArtifactName: 'TestResults'
      publishLocation: 'Container'
    displayName: 'Publishing Test Results'

  # Publish XML Reports
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'output.xml'
      searchFolder: $(testResultsDir)
      mergeTestResults: true
      failTaskOnFailedTests: true
    displayName: 'Publish JUnit Reports'
