trigger:
  - main

pool:
   vmImage: 'Windows-latest'

steps:
    #Setup Python 
   - task: UsePythonVersion@0
     inputs:
      versionSpec: '3.x'
      addToPath: true
      architecture: 'x64'
      allowUnstable: false
     displayName: 'Install Python'

     # Install Dependencies
   - script: |
        python  -m pip install --upgrade pip
        pip install -r requirements.txt
     displayName: 'Install Dependencies'
  
     # Run Tests
   - script: |
        robot tests/
     displayName: 'Running Robot Tests'
     
   - task: PublishBuildArtifacts@1
     inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
     displayName: 'Publishing Results' 
