trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  testResultsDir: '$(Build.ArtifactStagingDirectory)'

steps:
  # Setup Python
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
    displayName: 'Install Python'

  # Install Dependencies
  - script: |
      if not exist requirements.txt (
        echo "Error: requirements.txt not found!" && exit /b 1
      )
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Dependencies'

  # Run Tests
  - script: |
      mkdir $(testResultsDir)
      pabot --processes 8 --outputdir $(testResultsDir)  --report ${reportFileName}  --output ${outputFileName} -x outputxunit.xml  /TestCases
    displayName: 'Running Robot Tests'

  # Publish Results Directory
  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: '$(testResultsDir)'
      ArtifactName: 'TestResults'
      publishLocation: 'Container'
    displayName: 'Publishing Test Results'

  # Publish XML Reports
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '${testResultsDir}/**/outputxunit.xml'
      mergeTestResults: true
      failTaskOnFailedTests: true
    displayName: 'Publish JUnit Reports'